/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayCodeRouteImport } from './routes/play.$code'
import { Route as TableCodeRouteImport } from './routes/table.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TableCodeRoute = TableCodeRouteImport.update({
  id: '/table/$code',
  path: '/table/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play/$code': typeof PlayCodeRoute
  '/table/$code': typeof TableCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play/$code': typeof PlayCodeRoute
  '/table/$code': typeof TableCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play/$code': typeof PlayCodeRoute
  '/table/$code': typeof TableCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/play/$code' | '/table/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/play/$code' | '/table/$code'
  id: '__root__' | '/' | '/play/$code' | '/table/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayCodeRoute: typeof PlayCodeRoute
  TableCodeRoute: typeof TableCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$code': {
      id: '/table/$code'
      path: '/table/$code'
      fullPath: '/table/$code'
      preLoaderRoute: typeof TableCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayCodeRoute: PlayCodeRoute,
  TableCodeRoute: TableCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
