/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayCodeRouteImport } from './routes/play.$code'
import { Route as TableCodeRouteImport } from './routes/table.$code'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioProjectIdRouteImport } from './routes/studio.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TableCodeRoute = TableCodeRouteImport.update({
  id: '/table/$code',
  path: '/table/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioProjectIdRoute = StudioProjectIdRouteImport.update({
  id: '/studio/$projectId',
  path: '/studio/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play/$code': typeof PlayCodeRoute
  '/table/$code': typeof TableCodeRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/studio': typeof StudioIndexRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play/$code': typeof PlayCodeRoute
  '/table/$code': typeof TableCodeRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/studio': typeof StudioIndexRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play/$code': typeof PlayCodeRoute
  '/table/$code': typeof TableCodeRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/play/$code'
    | '/table/$code'
    | '/project/$projectId'
    | '/studio'
    | '/studio/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/play/$code'
    | '/table/$code'
    | '/project/$projectId'
    | '/studio'
    | '/studio/$projectId'
  id:
    | '__root__'
    | '/'
    | '/play/$code'
    | '/table/$code'
    | '/project/$projectId'
    | '/studio/'
    | '/studio/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayCodeRoute: typeof PlayCodeRoute
  TableCodeRoute: typeof TableCodeRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioProjectIdRoute: typeof StudioProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$code': {
      id: '/table/$code'
      path: '/table/$code'
      fullPath: '/table/$code'
      preLoaderRoute: typeof TableCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$projectId': {
      id: '/studio/$projectId'
      path: '/studio/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof StudioProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayCodeRoute: PlayCodeRoute,
  TableCodeRoute: TableCodeRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioProjectIdRoute: StudioProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
